import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Utility to merge class names using clsx and tailwind-merge.
 * Mirrors the helper generated by shadcn UI.
 */
export function cn(...inputs) {
  return twMerge(clsx(inputs));
}
